### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_c')

### ISSUE THREAD

**Issue by Gismo1337** [iMuMz/NovaMapCard#4]

**Comment by kishan93** [comment]
I am facing same issue:
```
runtime-core.esm-bundler.js:226 TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.render (nova-map-card:1:464778)
    at zn (runtime-core.esm-bundler.js:893:44)
    at we.fn (runtime-core.esm-bundler.js:5030:57)
    at we.run (reactivity.esm-bundler.js:167:25)
    at R (runtime-core.esm-bundler.js:5156:9)
    at j (runtime-core.esm-bundler.js:4939:9)
    at N (runtime-core.esm-bundler.js:4897:17)
    at g (runtime-core.esm-bundler.js:4489:21)
    at we.fn (runtime-core.esm-bundler.js:5037:21)
    at we.run (reactivity.esm-bundler.js:167:25)
```

**Comment by iMuMz** [comment]
What version of Nova are you using? The package isn't compatible with version 4 yet.

**Comment by kishan93** [comment]
yes I am using Nova 4

**Comment by iMuMz** [comment]
A Nova 4 compatible package is now available 

https://github.com/iMuMz/Nova4CardMap
